// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLimiter creates a new instance of MockLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLimiter {
	mock := &MockLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLimiter is an autogenerated mock type for the Limiter type
type MockLimiter struct {
	mock.Mock
}

type MockLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLimiter) EXPECT() *MockLimiter_Expecter {
	return &MockLimiter_Expecter{mock: &_m.Mock}
}

// AllowRequest provides a mock function for the type MockLimiter
func (_mock *MockLimiter) AllowRequest(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for AllowRequest")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLimiter_AllowRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllowRequest'
type MockLimiter_AllowRequest_Call struct {
	*mock.Call
}

// AllowRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockLimiter_Expecter) AllowRequest(ctx interface{}, key interface{}) *MockLimiter_AllowRequest_Call {
	return &MockLimiter_AllowRequest_Call{Call: _e.mock.On("AllowRequest", ctx, key)}
}

func (_c *MockLimiter_AllowRequest_Call) Run(run func(ctx context.Context, key string)) *MockLimiter_AllowRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLimiter_AllowRequest_Call) Return(b bool, err error) *MockLimiter_AllowRequest_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockLimiter_AllowRequest_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockLimiter_AllowRequest_Call {
	_c.Call.Return(run)
	return _c
}
