all: false
dir: '{{.InterfaceDir}}/mocks'
filename: '{{.InterfaceName}}_mock.go'
formatter: goimports
generate: true
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: mocks
template: testify
packages:
  github.com/StewardMcCormick/Paste_Bin/internal/usecase/auth:
    interfaces:
      Security:
      Validator:
      UnitOfWorkFactory:
  github.com/StewardMcCormick/Paste_Bin/internal/repository:
    interfaces:
      NoTxUnitOfWork:
      TxUnitOfWork:
      UserRepository:
      APIKeyRepository:

  github.com/StewardMcCormick/Paste_Bin/internal/usecase/paste:
    interfaces:
      Repository:
      CreateRequestValidator:
      UpdateRequestValidator:
      Security:
      ViewWorker:
  github.com/StewardMcCormick/Paste_Bin/internal/handler/paste:
    interfaces:
      UseCase:

  github.com/StewardMcCormick/Paste_Bin/internal/handler/user:
    interfaces:
      UseCase:

  github.com/StewardMcCormick/Paste_Bin/internal/handler/middleware:
    interfaces:
      AuthService:
      Limiter: