app:
  name: "Paste-Bin-App"
  version: "v1.0.0"
  env: "dev"

logger:
  level: "debug"
  outputs: [ "stdout" ]

postgres:
  connection_config:
    connection_timeout: "5s"
    max_connections: 15
    min_connections: 0
    max_connection_live_time: "1h"
    max_connection_idle_time: "30m"
    health_check_period: "1m"
  migrations_path: "./internal/migrations/postgres"

auth:
  api_key_expires_time: "168h"
