// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StewardMcCormick/Paste_Bin/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAPIKeyRepository creates a new instance of MockAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAPIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type MockAPIKeyRepository struct {
	mock.Mock
}

type MockAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepository_Expecter {
	return &MockAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) Create(ctx context.Context, userId int64, key *domain.APIKey) (*domain.APIKey, error) {
	ret := _mock.Called(ctx, userId, key)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.APIKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.APIKey) (*domain.APIKey, error)); ok {
		return returnFunc(ctx, userId, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *domain.APIKey) *domain.APIKey); ok {
		r0 = returnFunc(ctx, userId, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.APIKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *domain.APIKey) error); ok {
		r1 = returnFunc(ctx, userId, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAPIKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int64
//   - key *domain.APIKey
func (_e *MockAPIKeyRepository_Expecter) Create(ctx interface{}, userId interface{}, key interface{}) *MockAPIKeyRepository_Create_Call {
	return &MockAPIKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, userId, key)}
}

func (_c *MockAPIKeyRepository_Create_Call) Run(run func(ctx context.Context, userId int64, key *domain.APIKey)) *MockAPIKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *domain.APIKey
		if args[2] != nil {
			arg2 = args[2].(*domain.APIKey)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) Return(aPIKey *domain.APIKey, err error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(aPIKey, err)
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userId int64, key *domain.APIKey) (*domain.APIKey, error)) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeKeyByUserId provides a mock function for the type MockAPIKeyRepository
func (_mock *MockAPIKeyRepository) RevokeKeyByUserId(ctx context.Context, userId int64) error {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for RevokeKeyByUserId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAPIKeyRepository_RevokeKeyByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeKeyByUserId'
type MockAPIKeyRepository_RevokeKeyByUserId_Call struct {
	*mock.Call
}

// RevokeKeyByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int64
func (_e *MockAPIKeyRepository_Expecter) RevokeKeyByUserId(ctx interface{}, userId interface{}) *MockAPIKeyRepository_RevokeKeyByUserId_Call {
	return &MockAPIKeyRepository_RevokeKeyByUserId_Call{Call: _e.mock.On("RevokeKeyByUserId", ctx, userId)}
}

func (_c *MockAPIKeyRepository_RevokeKeyByUserId_Call) Run(run func(ctx context.Context, userId int64)) *MockAPIKeyRepository_RevokeKeyByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAPIKeyRepository_RevokeKeyByUserId_Call) Return(err error) *MockAPIKeyRepository_RevokeKeyByUserId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAPIKeyRepository_RevokeKeyByUserId_Call) RunAndReturn(run func(ctx context.Context, userId int64) error) *MockAPIKeyRepository_RevokeKeyByUserId_Call {
	_c.Call.Return(run)
	return _c
}
