// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/StewardMcCormick/Paste_Bin/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNoTxUnitOfWork creates a new instance of MockNoTxUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoTxUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoTxUnitOfWork {
	mock := &MockNoTxUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoTxUnitOfWork is an autogenerated mock type for the NoTxUnitOfWork type
type MockNoTxUnitOfWork struct {
	mock.Mock
}

type MockNoTxUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoTxUnitOfWork) EXPECT() *MockNoTxUnitOfWork_Expecter {
	return &MockNoTxUnitOfWork_Expecter{mock: &_m.Mock}
}

// APIKeyRepository provides a mock function for the type MockNoTxUnitOfWork
func (_mock *MockNoTxUnitOfWork) APIKeyRepository() repository.APIKeyRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for APIKeyRepository")
	}

	var r0 repository.APIKeyRepository
	if returnFunc, ok := ret.Get(0).(func() repository.APIKeyRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.APIKeyRepository)
		}
	}
	return r0
}

// MockNoTxUnitOfWork_APIKeyRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'APIKeyRepository'
type MockNoTxUnitOfWork_APIKeyRepository_Call struct {
	*mock.Call
}

// APIKeyRepository is a helper method to define mock.On call
func (_e *MockNoTxUnitOfWork_Expecter) APIKeyRepository() *MockNoTxUnitOfWork_APIKeyRepository_Call {
	return &MockNoTxUnitOfWork_APIKeyRepository_Call{Call: _e.mock.On("APIKeyRepository")}
}

func (_c *MockNoTxUnitOfWork_APIKeyRepository_Call) Run(run func()) *MockNoTxUnitOfWork_APIKeyRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNoTxUnitOfWork_APIKeyRepository_Call) Return(aPIKeyRepository repository.APIKeyRepository) *MockNoTxUnitOfWork_APIKeyRepository_Call {
	_c.Call.Return(aPIKeyRepository)
	return _c
}

func (_c *MockNoTxUnitOfWork_APIKeyRepository_Call) RunAndReturn(run func() repository.APIKeyRepository) *MockNoTxUnitOfWork_APIKeyRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepository provides a mock function for the type MockNoTxUnitOfWork
func (_mock *MockNoTxUnitOfWork) UserRepository() repository.UserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 repository.UserRepository
	if returnFunc, ok := ret.Get(0).(func() repository.UserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserRepository)
		}
	}
	return r0
}

// MockNoTxUnitOfWork_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type MockNoTxUnitOfWork_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
func (_e *MockNoTxUnitOfWork_Expecter) UserRepository() *MockNoTxUnitOfWork_UserRepository_Call {
	return &MockNoTxUnitOfWork_UserRepository_Call{Call: _e.mock.On("UserRepository")}
}

func (_c *MockNoTxUnitOfWork_UserRepository_Call) Run(run func()) *MockNoTxUnitOfWork_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNoTxUnitOfWork_UserRepository_Call) Return(userRepository repository.UserRepository) *MockNoTxUnitOfWork_UserRepository_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockNoTxUnitOfWork_UserRepository_Call) RunAndReturn(run func() repository.UserRepository) *MockNoTxUnitOfWork_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}
