// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StewardMcCormick/Paste_Bin/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxUnitOfWork creates a new instance of MockTxUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxUnitOfWork {
	mock := &MockTxUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxUnitOfWork is an autogenerated mock type for the TxUnitOfWork type
type MockTxUnitOfWork struct {
	mock.Mock
}

type MockTxUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxUnitOfWork) EXPECT() *MockTxUnitOfWork_Expecter {
	return &MockTxUnitOfWork_Expecter{mock: &_m.Mock}
}

// APIKeyRepository provides a mock function for the type MockTxUnitOfWork
func (_mock *MockTxUnitOfWork) APIKeyRepository() repository.APIKeyRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for APIKeyRepository")
	}

	var r0 repository.APIKeyRepository
	if returnFunc, ok := ret.Get(0).(func() repository.APIKeyRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.APIKeyRepository)
		}
	}
	return r0
}

// MockTxUnitOfWork_APIKeyRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'APIKeyRepository'
type MockTxUnitOfWork_APIKeyRepository_Call struct {
	*mock.Call
}

// APIKeyRepository is a helper method to define mock.On call
func (_e *MockTxUnitOfWork_Expecter) APIKeyRepository() *MockTxUnitOfWork_APIKeyRepository_Call {
	return &MockTxUnitOfWork_APIKeyRepository_Call{Call: _e.mock.On("APIKeyRepository")}
}

func (_c *MockTxUnitOfWork_APIKeyRepository_Call) Run(run func()) *MockTxUnitOfWork_APIKeyRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxUnitOfWork_APIKeyRepository_Call) Return(aPIKeyRepository repository.APIKeyRepository) *MockTxUnitOfWork_APIKeyRepository_Call {
	_c.Call.Return(aPIKeyRepository)
	return _c
}

func (_c *MockTxUnitOfWork_APIKeyRepository_Call) RunAndReturn(run func() repository.APIKeyRepository) *MockTxUnitOfWork_APIKeyRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockTxUnitOfWork
func (_mock *MockTxUnitOfWork) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxUnitOfWork_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTxUnitOfWork_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTxUnitOfWork_Expecter) Commit(ctx interface{}) *MockTxUnitOfWork_Commit_Call {
	return &MockTxUnitOfWork_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockTxUnitOfWork_Commit_Call) Run(run func(ctx context.Context)) *MockTxUnitOfWork_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTxUnitOfWork_Commit_Call) Return(err error) *MockTxUnitOfWork_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxUnitOfWork_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *MockTxUnitOfWork_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockTxUnitOfWork
func (_mock *MockTxUnitOfWork) Rollback(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockTxUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTxUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTxUnitOfWork_Expecter) Rollback(ctx interface{}) *MockTxUnitOfWork_Rollback_Call {
	return &MockTxUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockTxUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockTxUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTxUnitOfWork_Rollback_Call) Return() *MockTxUnitOfWork_Rollback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTxUnitOfWork_Rollback_Call) RunAndReturn(run func(ctx context.Context)) *MockTxUnitOfWork_Rollback_Call {
	_c.Run(run)
	return _c
}

// UserRepository provides a mock function for the type MockTxUnitOfWork
func (_mock *MockTxUnitOfWork) UserRepository() repository.UserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 repository.UserRepository
	if returnFunc, ok := ret.Get(0).(func() repository.UserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.UserRepository)
		}
	}
	return r0
}

// MockTxUnitOfWork_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type MockTxUnitOfWork_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
func (_e *MockTxUnitOfWork_Expecter) UserRepository() *MockTxUnitOfWork_UserRepository_Call {
	return &MockTxUnitOfWork_UserRepository_Call{Call: _e.mock.On("UserRepository")}
}

func (_c *MockTxUnitOfWork_UserRepository_Call) Run(run func()) *MockTxUnitOfWork_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTxUnitOfWork_UserRepository_Call) Return(userRepository repository.UserRepository) *MockTxUnitOfWork_UserRepository_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockTxUnitOfWork_UserRepository_Call) RunAndReturn(run func() repository.UserRepository) *MockTxUnitOfWork_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}
