// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/StewardMcCormick/Paste_Bin/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreateRequestValidator creates a new instance of MockCreateRequestValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateRequestValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateRequestValidator {
	mock := &MockCreateRequestValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreateRequestValidator is an autogenerated mock type for the CreateRequestValidator type
type MockCreateRequestValidator struct {
	mock.Mock
}

type MockCreateRequestValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateRequestValidator) EXPECT() *MockCreateRequestValidator_Expecter {
	return &MockCreateRequestValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockCreateRequestValidator
func (_mock *MockCreateRequestValidator) Validate(request *dto.PasteRequest) error {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*dto.PasteRequest) error); ok {
		r0 = returnFunc(request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreateRequestValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockCreateRequestValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - request *dto.PasteRequest
func (_e *MockCreateRequestValidator_Expecter) Validate(request interface{}) *MockCreateRequestValidator_Validate_Call {
	return &MockCreateRequestValidator_Validate_Call{Call: _e.mock.On("Validate", request)}
}

func (_c *MockCreateRequestValidator_Validate_Call) Run(run func(request *dto.PasteRequest)) *MockCreateRequestValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.PasteRequest
		if args[0] != nil {
			arg0 = args[0].(*dto.PasteRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCreateRequestValidator_Validate_Call) Return(err error) *MockCreateRequestValidator_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreateRequestValidator_Validate_Call) RunAndReturn(run func(request *dto.PasteRequest) error) *MockCreateRequestValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
