// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecurity creates a new instance of MockSecurity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecurity(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecurity {
	mock := &MockSecurity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecurity is an autogenerated mock type for the Security type
type MockSecurity struct {
	mock.Mock
}

type MockSecurity_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecurity) EXPECT() *MockSecurity_Expecter {
	return &MockSecurity_Expecter{mock: &_m.Mock}
}

// CompareHashAndPassword provides a mock function for the type MockSecurity
func (_mock *MockSecurity) CompareHashAndPassword(hash string, pass string) bool {
	ret := _mock.Called(hash, pass)

	if len(ret) == 0 {
		panic("no return value specified for CompareHashAndPassword")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(hash, pass)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSecurity_CompareHashAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareHashAndPassword'
type MockSecurity_CompareHashAndPassword_Call struct {
	*mock.Call
}

// CompareHashAndPassword is a helper method to define mock.On call
//   - hash string
//   - pass string
func (_e *MockSecurity_Expecter) CompareHashAndPassword(hash interface{}, pass interface{}) *MockSecurity_CompareHashAndPassword_Call {
	return &MockSecurity_CompareHashAndPassword_Call{Call: _e.mock.On("CompareHashAndPassword", hash, pass)}
}

func (_c *MockSecurity_CompareHashAndPassword_Call) Run(run func(hash string, pass string)) *MockSecurity_CompareHashAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecurity_CompareHashAndPassword_Call) Return(b bool) *MockSecurity_CompareHashAndPassword_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSecurity_CompareHashAndPassword_Call) RunAndReturn(run func(hash string, pass string) bool) *MockSecurity_CompareHashAndPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GeneratePasteHash provides a mock function for the type MockSecurity
func (_mock *MockSecurity) GeneratePasteHash() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GeneratePasteHash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecurity_GeneratePasteHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratePasteHash'
type MockSecurity_GeneratePasteHash_Call struct {
	*mock.Call
}

// GeneratePasteHash is a helper method to define mock.On call
func (_e *MockSecurity_Expecter) GeneratePasteHash() *MockSecurity_GeneratePasteHash_Call {
	return &MockSecurity_GeneratePasteHash_Call{Call: _e.mock.On("GeneratePasteHash")}
}

func (_c *MockSecurity_GeneratePasteHash_Call) Run(run func()) *MockSecurity_GeneratePasteHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSecurity_GeneratePasteHash_Call) Return(s string, err error) *MockSecurity_GeneratePasteHash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSecurity_GeneratePasteHash_Call) RunAndReturn(run func() (string, error)) *MockSecurity_GeneratePasteHash_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function for the type MockSecurity
func (_mock *MockSecurity) HashPassword(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecurity_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockSecurity_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockSecurity_Expecter) HashPassword(password interface{}) *MockSecurity_HashPassword_Call {
	return &MockSecurity_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockSecurity_HashPassword_Call) Run(run func(password string)) *MockSecurity_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecurity_HashPassword_Call) Return(s string, err error) *MockSecurity_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSecurity_HashPassword_Call) RunAndReturn(run func(password string) (string, error)) *MockSecurity_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}
