// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/StewardMcCormick/Paste_Bin/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdateRequestValidator creates a new instance of MockUpdateRequestValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateRequestValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateRequestValidator {
	mock := &MockUpdateRequestValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdateRequestValidator is an autogenerated mock type for the UpdateRequestValidator type
type MockUpdateRequestValidator struct {
	mock.Mock
}

type MockUpdateRequestValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdateRequestValidator) EXPECT() *MockUpdateRequestValidator_Expecter {
	return &MockUpdateRequestValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockUpdateRequestValidator
func (_mock *MockUpdateRequestValidator) Validate(request *dto.UpdatePasteRequest) error {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*dto.UpdatePasteRequest) error); ok {
		r0 = returnFunc(request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUpdateRequestValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockUpdateRequestValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - request *dto.UpdatePasteRequest
func (_e *MockUpdateRequestValidator_Expecter) Validate(request interface{}) *MockUpdateRequestValidator_Validate_Call {
	return &MockUpdateRequestValidator_Validate_Call{Call: _e.mock.On("Validate", request)}
}

func (_c *MockUpdateRequestValidator_Validate_Call) Run(run func(request *dto.UpdatePasteRequest)) *MockUpdateRequestValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.UpdatePasteRequest
		if args[0] != nil {
			arg0 = args[0].(*dto.UpdatePasteRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUpdateRequestValidator_Validate_Call) Return(err error) *MockUpdateRequestValidator_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUpdateRequestValidator_Validate_Call) RunAndReturn(run func(request *dto.UpdatePasteRequest) error) *MockUpdateRequestValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
