// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/StewardMcCormick/Paste_Bin/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Create(ctx context.Context, request *dto.PasteRequest) (*dto.PasteResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *dto.PasteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.PasteRequest) (*dto.PasteResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.PasteRequest) *dto.PasteResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PasteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.PasteRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dto.PasteRequest
func (_e *MockUseCase_Expecter) Create(ctx interface{}, request interface{}) *MockUseCase_Create_Call {
	return &MockUseCase_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *MockUseCase_Create_Call) Run(run func(ctx context.Context, request *dto.PasteRequest)) *MockUseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.PasteRequest
		if args[1] != nil {
			arg1 = args[1].(*dto.PasteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_Create_Call) Return(pasteResponse *dto.PasteResponse, err error) *MockUseCase_Create_Call {
	_c.Call.Return(pasteResponse, err)
	return _c
}

func (_c *MockUseCase_Create_Call) RunAndReturn(run func(ctx context.Context, request *dto.PasteRequest) (*dto.PasteResponse, error)) *MockUseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetByHash(ctx context.Context, request dto.GetPasteRequest, hash string) (*dto.PasteResponse, error) {
	ret := _mock.Called(ctx, request, hash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *dto.PasteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetPasteRequest, string) (*dto.PasteResponse, error)); ok {
		return returnFunc(ctx, request, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.GetPasteRequest, string) *dto.PasteResponse); ok {
		r0 = returnFunc(ctx, request, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PasteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.GetPasteRequest, string) error); ok {
		r1 = returnFunc(ctx, request, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockUseCase_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - request dto.GetPasteRequest
//   - hash string
func (_e *MockUseCase_Expecter) GetByHash(ctx interface{}, request interface{}, hash interface{}) *MockUseCase_GetByHash_Call {
	return &MockUseCase_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, request, hash)}
}

func (_c *MockUseCase_GetByHash_Call) Run(run func(ctx context.Context, request dto.GetPasteRequest, hash string)) *MockUseCase_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.GetPasteRequest
		if args[1] != nil {
			arg1 = args[1].(dto.GetPasteRequest)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_GetByHash_Call) Return(pasteResponse *dto.PasteResponse, err error) *MockUseCase_GetByHash_Call {
	_c.Call.Return(pasteResponse, err)
	return _c
}

func (_c *MockUseCase_GetByHash_Call) RunAndReturn(run func(ctx context.Context, request dto.GetPasteRequest, hash string) (*dto.PasteResponse, error)) *MockUseCase_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaste provides a mock function for the type MockUseCase
func (_mock *MockUseCase) UpdatePaste(ctx context.Context, hash string, request *dto.UpdatePasteRequest) (*dto.PasteResponse, error) {
	ret := _mock.Called(ctx, hash, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaste")
	}

	var r0 *dto.PasteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.UpdatePasteRequest) (*dto.PasteResponse, error)); ok {
		return returnFunc(ctx, hash, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *dto.UpdatePasteRequest) *dto.PasteResponse); ok {
		r0 = returnFunc(ctx, hash, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PasteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *dto.UpdatePasteRequest) error); ok {
		r1 = returnFunc(ctx, hash, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_UpdatePaste_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaste'
type MockUseCase_UpdatePaste_Call struct {
	*mock.Call
}

// UpdatePaste is a helper method to define mock.On call
//   - ctx context.Context
//   - hash string
//   - request *dto.UpdatePasteRequest
func (_e *MockUseCase_Expecter) UpdatePaste(ctx interface{}, hash interface{}, request interface{}) *MockUseCase_UpdatePaste_Call {
	return &MockUseCase_UpdatePaste_Call{Call: _e.mock.On("UpdatePaste", ctx, hash, request)}
}

func (_c *MockUseCase_UpdatePaste_Call) Run(run func(ctx context.Context, hash string, request *dto.UpdatePasteRequest)) *MockUseCase_UpdatePaste_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *dto.UpdatePasteRequest
		if args[2] != nil {
			arg2 = args[2].(*dto.UpdatePasteRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_UpdatePaste_Call) Return(pasteResponse *dto.PasteResponse, err error) *MockUseCase_UpdatePaste_Call {
	_c.Call.Return(pasteResponse, err)
	return _c
}

func (_c *MockUseCase_UpdatePaste_Call) RunAndReturn(run func(ctx context.Context, hash string, request *dto.UpdatePasteRequest) (*dto.PasteResponse, error)) *MockUseCase_UpdatePaste_Call {
	_c.Call.Return(run)
	return _c
}
